/* 회원 */
CREATE TABLE MEMBER (
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	PASSWORD VARCHAR2(20) NOT NULL, /* 비밀번호 */
	NAME VARCHAR2(20) NOT NULL, /* 이름 */
	TEL VARCHAR2(20) NOT NULL, /* 전화번호 */
	EMAIL VARCHAR2(40) NOT NULL, /* 이메일 */
	CONSTRAINT PK_MEMBER PRIMARY KEY(ID)
);

/* 회원 정보 */
CREATE TABLE MEMBER_INFO (
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	NICKNAME VARCHAR2(20), /* 닉네임 */
	GENDER VARCHAR2(6), /* 성별 */
	AGE NUMBER, /* 나이 */
	LOCALE VARCHAR2(20), /* 지역 */
	JOB VARCHAR2(20), /* 직업 */
	JOB_LOCALE VARCHAR2(20), /* 직장 지역 */
	CONSTRAINT PK_MEMBER_INFO PRIMARY KEY(ID),
	CONSTRAINT FK_MEMBER_TO_MEMBER_INFO FOREIGN KEY(ID)
	REFERENCES MEMBER(ID) ON DELETE CASCADE
)

/* 게시판 */
CREATE TABLE BOARD (
	COUNT NUMBER NOT NULL, /* 글번호 */
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	TITLE VARCHAR2(100) NOT NULL, /* 제목 */
	BODY VARCHAR2(500) NOT NULL, /* 내용 */
	VIEW_COUNT NUMBER DEFAULT 0, /* 조회수 */
	WRITE_DATE VARCHAR2(30) NOT NULL, /* 작성일 */
	CONSTRAINT PK_BOARD PRIMARY KEY(COUNT,ID),
	CONSTRAINT FK_MEMBER_TO_BOARD FOREIGN KEY(ID)
		REFERENCES MEMBER (ID) ON DELETE CASCADE
)

/* 자유게시판 */
CREATE TABLE FREE_BOARD (
	COUNT NUMBER NOT NULL, /* 글번호 */
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	FB_FILE VARCHAR2(100), /* 파일 */
	FB_WEATHER VARCHAR2(20), /* 날씨정보 */
	CONSTRAINT PK_FREE_BOARD PRIMARY KEY(COUNT,ID),
	CONSTRAINT FK_BOARD_TO_FREE_BOARD FOREIGN KEY(COUNT,ID)
	REFERENCES BOARD(COUNT,ID) ON DELETE CASCADE
)

/* 사진 게시판 */
CREATE TABLE PHOTO_BOARD (
	COUNT NUMBER NOT NULL, /* 글번호 */
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	FB_FILE VARCHAR2(100), /* 사진 */
	PB_COUNT NUMBER DEFAULT 0, /* 추천수 */
	FB_WEATHER VARCHAR2(20), /* 날씨정보 */
	CONSTRAINT PK_PHOTO_BOARD PRIMARY KEY(COUNT,ID),
	CONSTRAINT FK_BOARD_TO_PHOTO_BOARD FOREIGN KEY(COUNT,ID)
	REFERENCES BOARD(COUNT,ID) ON DELETE CASCADE
)

/* 캘린더 */
CREATE TABLE CALENDAR (
	C_DATE VARCHAR2(30) NOT NULL, /* 날짜 */
	F_RANKED NUMBER, /* 랭킹 게시물 */
	S_RANKED NUMBER, /* 랭킹 게시물2 */
	T_RANKED NUMBER, /* 랭킹 게시물3 */
	C_WEATHER VARCHAR2(20), /* 날씨 정보 */
	CONSTRAINT PK_CALENDAR PRIMARY KEY(C_DATE)
);
